export LANG=ru_RU.UTF-8
export LC_ALL=ru_RU.UTF-8
export LC_CTYPE=ru_RU.UTF-8

export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
export PATH="/usr/local/opt/openldap/bin:$PATH"
export PATH="/usr/local/opt/openldap/sbin:$PATH"
export PATH="/usr/local/opt/curl-openssl/bin:$PATH"
export PATH="/usr/local/opt/net-snmp/bin:/usr/local/opt/net-snmp/sbin:$PATH"
export PATH="~/.php/bin:$PATH"

if [ -d "$HOME/perl5/bin" ]; then
	export PATH="$HOME/perl5/bin:$PATH"
	export PERL5LIB="$HOME/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"
	export PERL_LOCAL_LIB_ROOT="$HOME/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"
	export PERL_MB_OPT="--install_base \"$HOME/perl5\""
	export PERL_MM_OPT="INSTALL_BASE=$HOME/perl5"
fi

export DISPLAY=:0.0
export MANPATH=/opt/local/share/man:$MANPATH
export HISTFILESIZE=5000
export INPUTRC=~/.inputrc
export EDITOR="vim"
export PYTHONIOENCODING=UTF-8
export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache

if [ -f "$HOME/.not-public" ]; then
    . $HOME/.not-public
fi

export HOMEBREW_NO_EMOJI=1
export HOMEBREW_CASK_OPTS="--appdir=~/Applications --fontdir=/Library/Fonts"
if [ -f $(brew --prefix)/etc/bash_completion ]; then
	. $(brew --prefix)/etc/bash_completion
fi

if [ -f ~/.bash_aliases ]; then
	. ~/.bash_aliases
fi

if [ -d /Applications/VLC.app/Contents/MacOS ]; then
	PATH=$PATH:/Applications/VLC.app/Contents/MacOS
fi

export PATH="$HOME/.pyenv/bin:$PATH"
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
if which pyenv-virtualenv-init > /dev/null; then
	eval "$(pyenv init -)"
	eval "$(pyenv virtualenv-init -)"
fi

if [ -d "$HOME/bin" ]; then
	export PATH="$HOME/bin:$PATH"
fi

if [ -f ~/perl5/perlbrew/etc/bashrc ]; then
	eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"
	. ~/perl5/perlbrew/etc/bashrc
fi
